name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        braches: [ "main" ]

    # Allows the action to be run manually
    workflow_dispatch:

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Test
              run: echo Hello, world!
