name: Deploy

on:
    push:
        branches: [ "main" ]

    # Allows the action to be run manually
    workflow_dispatch:

jobs: 
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install iproute2
              run: sudo apt-get update && sudo apt-get install -y iproute2
              
            - name: Set up WireGuard
              uses: egor-tensin/setup-wireguard@v1.2.0
              with:
                endpoint: '${{ secrets.WIREGUARD_ENDPOINT }}'
                endpoint_public_key: '${{ secrets.WIREGUARD_ENDPOINT_PUBLIC_KEY }}'
                ips: '${{ secrets.WIREGUARD_IPS }}'
                allowed_ips: '${{ secrets.WIREGUARD_ALLOWED_IPS }}'
                private_key: '${{ secrets.WIREGUARD_PRIVATE_KEY }}'

            - name: Set up SSH
              id: ssh
              uses: invi5H/ssh-action@v1
              with:
                SSH_HOST: ${{ secrets.SSH_HOST }}
                SSH_PORT: ${{ secrets.SSH_PORT }}
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_KEY: ${{ secrets.SSH_KEY }}

            - name: Run Build Script Over SSH
              run: ssh ${{ steps.ssh.outputs.SERVER }} "/home/${{ secrets.SSH_USER }}/NeuraViz/src/build.sh"

